replicaCount: 1

image:
  repository: ghcr.io/stagecc/bdc-program-studies
  tag: "1.0.2"

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  type: ClusterIP
  port: 8080

ingress:
  host: bdc-program-studies.apps.renci.org
  path: /
  tls: true
  public: false
