name: "Push to Github Container Registry"

on:
  release:
    types: [published]

jobs:
  publish-bdc-program-studies:
    name: Push studies page to GitHub Container Registry.
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push bdc-program-studies
        uses: docker/build-push-action@v5
        with:
          build-args: VITE_DUG_SEARCH_API=https://search-dev.biodatacatalyst.renci.org
          platform: linux/amd64
          context: .
          file: ./Dockerfile
          push: true
          tags: latest,${{ steps.get_version.outputs.VERSION }}
